-- OPTIONAL sample feed. Existing rows with these IDs are preserved.
begin;
insert into public.localy_community_posts (workspace_id,id,data) values
('localy', 'post_1', '{"id":"post_1","author":"Alex Morgan","initials":"AM","source":"Facebook Group","community":"Cambridge Community","content":"Looking for a dog groomer in Cambridge tomorrow for my golden retriever. Hoping to stay under $100.","intent":"high","confidence":0.94,"time":"2 min ago","opportunityId":"opp_001","explanation":"Specific service, location, date, and budget. Ready to book."}'::jsonb),
('localy', 'post_2', '{"id":"post_2","author":"Jamie Chen","initials":"JC","source":"Reddit","community":"r/Somerville","content":"Anyone know a good groomer around Somerville? My little terrier could use a bath and brush this weekend.","intent":"medium","confidence":0.87,"time":"8 min ago","opportunityId":"opp_002","explanation":"Seeking a recommendation. Timing and budget need clarification."}'::jsonb),
('localy', 'post_social', '{"id":"post_social","author":"Chris Park","initials":"CP","source":"Discord","community":"Boston Dog Parents","content":"My dog absolutely hates baths 😂","intent":"low","confidence":0.96,"time":"12 min ago","explanation":"Casual conversation with no request for a service. Ignored."}'::jsonb),
('localy', 'post_vet', '{"id":"post_vet","author":"Nina Shah","initials":"NS","source":"Telegram","community":"Cambridge Neighbors","content":"Moving to Cambridge next month. Any recommendations for vets?","intent":"irrelevant","confidence":0.98,"time":"18 min ago","explanation":"Veterinary care is outside this business''s grooming services."}'::jsonb),
('localy', 'post_3', '{"id":"post_3","author":"Sam Rivera","initials":"SR","source":"Discord","community":"Boston Dog Parents","content":"Need someone to trim my dog''s nails today if possible. We''re in Boston and can come by this afternoon.","intent":"high","confidence":0.92,"time":"22 min ago","opportunityId":"opp_003","explanation":"A specific service with urgency. Check same-day availability before sending."}'::jsonb)
on conflict (workspace_id,id) do nothing;

insert into public.localy_opportunities (workspace_id,id,data) values
('localy', 'opp_001', '{"id":"opp_001","postId":"post_1","customer":"Alex Morgan","originalPost":"Looking for a dog groomer in Cambridge tomorrow for my golden retriever. Hoping to stay under $100.","source":"Facebook Group","community":"Cambridge Community","intent":{"service":"Full Dog Grooming","pet":"Golden Retriever","location":"Cambridge","date":"Tomorrow","budget":100,"purchaseIntent":"high","confidence":0.94},"match":{"score":0.96,"serviceId":"svc_groom","service":"Full Groom Package","price":85,"availableSlots":["11:00 AM","3:00 PM"],"checks":[{"label":"Service Match","passed":true},{"label":"Location Match","passed":true},{"label":"Budget Match","passed":true},{"label":"Breed Accepted","passed":true},{"label":"Availability","passed":true}]},"intentScore":0.94,"status":"new","detectedAt":"Just now","suggestedResponse":"Hi! I''m the AI assistant for Cambridge Pet Groomers. We offer full grooming for golden retrievers starting at $85, and we have openings tomorrow at 11 AM and 3 PM. Would you like more details?"}'::jsonb),
('localy', 'opp_002', '{"id":"opp_002","postId":"post_2","customer":"Jamie Chen","originalPost":"Anyone know a good groomer around Somerville? My little terrier could use a bath and brush this weekend.","source":"Reddit","community":"r/Somerville","intent":{"service":"Bath & Brush","pet":"Terrier","location":"Somerville","date":"This weekend","budget":70,"purchaseIntent":"medium","confidence":0.87},"match":{"score":0.89,"serviceId":"svc_bath","service":"Bath & Brush","price":55,"availableSlots":[],"checks":[{"label":"Service Match","passed":true},{"label":"Location Match","passed":true},{"label":"Budget Match","passed":true},{"label":"Breed Accepted","passed":true},{"label":"Availability","passed":false}]},"intentScore":0.68,"status":"new","detectedAt":"7 min ago","suggestedResponse":"Hi! I''m the AI assistant for Cambridge Pet Groomers. Our Bath & Brush is 55 dollars. Would you like us to check an appointment for your terrier?"}'::jsonb),
('localy', 'opp_003', '{"id":"opp_003","postId":"post_3","customer":"Sam Rivera","originalPost":"Need someone to trim my dog''s nails today if possible. We''re in Boston and can come by this afternoon.","source":"Discord","community":"Boston Dog Parents","intent":{"service":"Nail Trim","pet":"Labrador","location":"Boston","date":"Today","budget":30,"purchaseIntent":"high","confidence":0.87},"match":{"score":0.92,"serviceId":"svc_nails","service":"Nail Trim","price":20,"availableSlots":[],"checks":[{"label":"Service Match","passed":true},{"label":"Location Match","passed":true},{"label":"Budget Match","passed":true},{"label":"Breed Accepted","passed":true},{"label":"Availability","passed":false}]},"intentScore":0.94,"status":"new","detectedAt":"14 min ago","suggestedResponse":"Hi! I''m the AI assistant for Cambridge Pet Groomers. Our Nail Trim is 20 dollars. Would you like us to check an appointment for your labrador?"}'::jsonb)
on conflict (workspace_id,id) do nothing;
commit;
